# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Please write our copyright if you use this file.
# © 2023 Floorp Projects & Contributors

#! SELF HOST DOES NOT SUPPORTED
#TODO! buildjet config not implemented
#! Deb && aarch64 may not supported
#TODO: separate Publish to other workflow

#? In GitHub, boolean DOES NOT return `true`, DOES return `'true'`
#? So, In `if:`(github) or `if [];then`(bash), you may SHOULD write like
#? `if: ${{boolean == 'true'}}`(github), `if [ ${{boolean}} == 'true' ];then`(bash)
#? ref https://github.com/actions/runner/issues/1483
#? and in bash, space between [ and value is important like [ ${{}} ]
on:
  workflow_call:
    inputs:
      disable-updater:
        description: disable updator esp. for deb
        type: boolean
        default: false
      aarch64:
        description: "aarch64 option is not compartiable with deb option"
        type: boolean
        default: false
      with_raw:
        description: "with all files of dist(esp. for make mar)"
        type: boolean
        default: false



# name: Linux Build
# description: Action of Floorp Linux build (x64, aarch64)

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:

    - name: Change PPA mirror servers
      run: |
        sudo perl -p -i -e 's%(deb(?:-src|)\s+)https?://(?!archive\.canonical\.com|security\.ubuntu\.com)[^\s]+%$1http://archive.ubuntu.com/ubuntu/%' /etc/apt/sources.list
        sudo apt update


    #! ON UBUNTU RUNNER
    - name: Setup Disk & Swap Space 💿
      run: |
        echo Before:
        free -h
        df -h
        echo
        echo
        sudo swapoff /mnt/swapfile
        sudo rm /mnt/swapfile

        sudo fallocate -l 8G /mnt/swapfile
        sudo chmod 600 /mnt/swapfile
        sudo mkswap /mnt/swapfile
        sudo swapon /mnt/swapfile

        sudo apt clean
        # dpkg --list |grep "^rc" | cut -d " " -f 3 | xargs sudo dpkg --purge
        sudo apt remove temurin* openjdk*
        sudo apt remove microsoft-edge* firefox* google-chrome*
        sudo apt remove mono* libmono* msbuild* dotnet*
        sudo apt remove llvm-15* llvm-14* llvm-13* llvm-12* libllvm15* libllvm14* libllvm13* libllvm12*
        sudo apt remove gfortran* php* julia* r-*
        sudo apt remove mysql* postgresql*
        sudo apt remove google-cloud-sdk azure-cli powershell snapd

        sudo rm -rf /usr/share/swift &
        sudo rm -rf /usr/local/aws-cli &
        sudo rm -rf /usr/local/aws-sam-cli &
        sudo rm -rf /usr/local/julia* &
        sudo rm -rf /usr/local/lib/android &
        sudo rm -rf /usr/local/lib/node_modules &
        sudo rm -rf /opt/hostedtoolcache &
        sudo rm -rf /opt/pipx &
        sudo rm -rf /snap &
        wait

        sudo fallocate -l 12G /home/runner/swapfile
        sudo chmod 600 /home/runner/swapfile
        sudo mkswap /home/runner/swapfile
        sudo swapon /home/runner/swapfile
        # sudo fallocate -l 10G /home/runner/swapfile2
        # sudo chmod 600 /home/runner/swapfile2
        # sudo mkswap /home/runner/swapfile2
        # sudo swapon /home/runner/swapfile2

        sudo sysctl vm.swappiness=10


        echo
        echo
        echo After:
        free -h
        df -h

    - uses: actions/checkout@v3
      name: Clone 🧬

    - name: Clone l10n-central 🧬
      uses: actions/checkout@v3
      with:
        repository: Floorp-Projects/l10n-central
        path: l10n-central

    - name: Prepare cross compiler (aarch64)⚒
      if: ${{ inputs.aarch64 && !inputs.deb }}
      run: |
        sudo apt update
        sudo apt -y install gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

    - name: setup Rust 🦀
      run: |
        if [[ $GHA_aarch64 == 'true' ]];then
          rustup target add aarch64-unknown-linux-gnu
        fi

        #? https://github.com/mozilla/sccache#known-caveats
        export CARGO_INCREMENTAL=0
      env:
        GHA_aarch64: ${{inputs.aarch64}}

    - name: Configure sccache
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Create environment 🌲
      run: |
        import os
        import sys
        import shutil

        disable_updater = os.environ["GHA_disable_updater"] == "true"
        aarch64 = os.environ["GHA_aarch64"] == "true"

        os.system("sudo apt update")
        os.system("sudo apt install xvfb")

        shutil.copyfile("./.github/mozconfig_linux_base","./mozconfig")
        # os.system("cp ./.github/mozconfig_linux_base ./mozconfig")

        mozconfig = []

        if disable_updater:
          mozconfig.append('ac_add_options --disable-updater')

        if aarch64:
          mozconfig += [
            ('ac_add_options --enable-rust-simd')
          , ('ac_add_options --target=aarch64-unknown-linux-gnu')
          ]

        if not aarch64:
          mozconfig.append('ac_add_options MOZ_PGO=1')

        # SCCACHE SETTINGS START
        mozconfig += [
          ("mk_add_options 'export RUSTC_WRAPPER=/home/runner/.mozbuild/sccache/sccache'")
        , ("mk_add_options 'export CCACHE_CPP2=yes'")
        , ("ac_add_options --with-ccache=/home/runner/.mozbuild/sccache/sccache")
        , ("mk_add_options 'export SCCACHE_GHA_ENABLED=on'")
        ]
        # SCCACHE SETTINGS END

        mozconfig_file = open("mozconfig",'a')
        mozconfig_file.writelines('\n'.join(mozconfig))

        mozconfig_file.close()
        os.system("cat mozconfig")
        os.system("./mach --no-interactive bootstrap --application-choice browser")

      env:
        GHA_disable_updater: ${{inputs.disable-updater}}
        GHA_aarch64: ${{inputs.aarch64}}
      shell: python3 {0}

    - name: Build 🔨

      run: |
        if [[ $GHA_aarch64 != 'true' ]]; then
          rm -rf ./l10n-central/.git
        fi

        Xvfb :2 -screen 0 1024x768x24 &
        export DISPLAY=:2

        export WORKDIR=`pwd`
        echo "Current Workdir: $WORKDIR"
        ./mach configure
        ./mach build
      env:
        GHA_aarch64: ${{inputs.aarch64}}

    - name: Package 1 - mach 🎁
      run: |
        ./mach package

        ./mach package-multi-locale --locales ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th vi zh-CN zh-TW

    - name: Package 2 - deb or zip 📦

      run: |
        # export MOZ_CHROME_MULTILOCALE="ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th vi zh-CN zh-TW"
        # for AB_CD in $MOZ_CHROME_MULTILOCALE; do    ./mach build chrome-$AB_CD; done
        # AB_CD=multi ./mach package
        # ./mach package-multi-locale --locales ar cs da de el en-GB en-US es-ES es-MX fr hu id it ja ko lt nl nn-NO pl pt-BR pt-PT ru sv-SE th vi zh-CN zh-TW

        # wait

        # FOR DEBUG 1 START

        sudo apt install tree

        #FOR DEBUG 1 END

        if [[ $GHA_aarch64 != 'true' ]];then
          echo "OUTPUT=obj-x86_64-pc-linux-gnu/dist/*.tar.bz2" >> $GITHUB_ENV
          # zip -r dist.zip obj-x86_64-pc-linux-gnu/dist/*.tar.bz2
        else
          #aarch64
          echo "OUTPUT=obj-aarch64-unknown-linux-gnu/dist/*.tar.bz2" >> $GITHUB_ENV
          # zip -r dist.zip obj-aarch64-unknown-linux-gnu/dist/*.tar.bz2
        fi

        if [[ $GHA_raw == 'true' ]];then
          if [[ $GHA_aarch64 != 'true' ]];then
            zip -r all.zip obj-x86_64-pc-linux-gnu/dist/*
          else
            zip -r all.zip obj-aarch64-unknown-linux-gnu/dist/*
          fi
        fi
      env:
        GHA_aarch64: ${{inputs.aarch64}}
        GHA_raw: ${{inputs.with_raw}}

    #PUBLISH START

    #! Deb && aarch64 may not supported
    - name: Publish🎁
      uses: actions/upload-artifact@v3
      with:
        name: floorp-linux-${{fromJson('["x64","aarch64"]')[inputs.aarch64]}}
        path: ${{ env.OUTPUT }}
        # path: dist.zip
    - name: Publish raw (only if with_raw)
      uses: actions/upload-artifact@v3
      if: inputs.with_raw
      with:
        name: floorp-linux-${{fromJson('["x64","aarch64"]')[inputs.aarch64]}}
        path: all.zip
    #PUBLISH END
