# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Please write our copyright if you use this file.
# © 2023 Floorp Projects & Contributors

name: "(U) 🧰 Close inactive issues"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open for 14 days with no activity. Remove stale label or comment to re-open."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          stale-issue-label: "stale"
          exempt-issue-labels: "bug"
          days-before-issue-stale: 14
          days-before-issue-close: 14
          days-before-pr-stale: -1
          days-before-pr-close: -1
